[workspace]
resolver = "2"
members = [
    "client",
    "common",
    "prover",
    "smart-contract",
    "state-database",
    "witness-database",
]

[workspace.dependencies]
# Crates.io dependencies.
ark-ff = { version = "0.3.0" }
thiserror = { version = "1.0" }
tokio = { version = "1.36.0", features = ["full"] }

# Git dependencies.
mina-curves.git = "https://github.com/o1-labs/proof-systems"
mina-poseidon.git = "https://github.com/o1-labs/proof-systems"

# Local dependencies.
common.path = "common"
