[workspace]
resolver = "2"
members = [
    "balances-db",
    "burns-db",
    "data-structures",
    "db",
    "deposit-tree",
    "queue",
    "liquidities-db",
    "list",
    "mempool",
    "merkle-tree",
    "pools-db",
    "poseidon-hash",
    "proof-submitter",
    "proofpool",
    "rollup",
    "rpc-server",
    "state-fetcher",
    "state-tree",
    "tx-status-list",
    "withdrawal-tree",
]

[workspace.dependencies]
# Crates.io dependencies.
ark-ff = { version = "0.3.0" }
thiserror = { version = "1.0" }
tokio = { version = "1.36.0", features = ["full"] }

# GitHub dependencies.
mina-curves.git = "https://github.com/o1-labs/proof-systems"
mina-poseidon.git = "https://github.com/o1-labs/proof-systems"

# Local dependencies.
data-structures.path = "data-structures"
poseidon-hash.path = "poseidon-hash"
merkle-tree.path = "merkle-tree"
