[workspace]
resolver = "2"
members = [
    "nacho-database",
    "nacho-prover",
    "nacho-proc-macros",
    "nacho-server",
    "nacho-merkle-tree",
    "nacho-types", 
    "nacho-poseidon-hash",
]

