pub const WITHDRAWALS_TREE_HEIGHT: usize = 19;

pub const WITHDRAWALS_TREE_SIBLING_COUNT: usize = WITHDRAWALS_TREE_HEIGHT - 1;

pub const WITHDRAWALS_TREE_MAX_LEAF_INDEX: u64 = 2_u64.pow(WITHDRAWALS_TREE_HEIGHT as u32 - 1) - 1;

pub const WITHDRAWALS_TREE_SIZE_IN_BYTES: u64 =
    32 * (2_u64.pow(WITHDRAWALS_TREE_HEIGHT as u32) - 1);

pub const WITHDRAWALS_TREE_ROOT_PADDING: u64 = 32 * (2_u64.pow(WITHDRAWALS_TREE_HEIGHT as u32) - 2);
