[package]
name = "nacho-dynamic-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Crates.io dependencies.
thiserror.workspace = true
tokio.workspace = true
