[package]
name = "schnorr-signature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nacho-data-structures.workspace = true

mina-signer.workspace = true
mina-hasher.workspace = true
