name: Node.js Tests

on:
    push:

jobs:
    token_contract:
        name: Token Contract Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./token-contract
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./token-contract/package-lock.json
            - run: npm install
            - run: npm test

    bridge_contract:
        name: Bridge Contract Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./bridge-contract
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./bridge-contract/package-lock.json
            - run: npm install
            - run: npm test

    rollup_contract:
        name: Rollup Contract Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./rollup-contract
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./rollup-contract/package-lock.json
            - run: npm install
            - run: npm test

    proof_generator:
        name: Proof Generator Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./proof-generator
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./proof-generator/package-lock.json
            - run: npm install
            - run: npm test
